version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/myapp
permissions:
  - object: /var/www/myapp
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  ApplicationStart:
    - location: scripts/application-start.sh
      timeout: 300
      runas: ubuntu
  ApplicationStop:
    - location: scripts/application-stop.sh
      timeout: 300
      runas: ubuntu
