version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 5.0
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore dotnetcorecicd.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet build  dotnetcorecicd.csproj
  post_build:
    commands:
      - echo Publish started on `date`
      # https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/dotnet-linux-platform-bundle-app.html
      - dotnet publish -c Release -r linux-x64 -o dotnetcorecicd.csproj
artifacts:
  files:
    - '**/*'  
  
